services:
  - type: web
    name: pomocare
    env: python
    plan: free
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FRUIT_GUARDIAN_SECRET
        sync: false
      - key: ADMIN_ACCESS_TOKEN
        sync: false

